spring:
  datasource:
    url: jdbc:h2:mem:todo
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console # access through: http://localhost:8080/todo-service/console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /todo-service

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never